import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider"
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

// const inter = Inter({ subsets: ["latin"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  suppressHydrationWarning cz-shortcut-listen="true">
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}